baseurl = "http://www.achter.be"
languageCode = "en-us"
title = "achter.be"
description = "photography, coffee, technology and more"

contentdir = "content"
layoutdir = "layouts"
publishdir = "public"
builddrafts = false
canonifyurls = false
paginate = 5
paginatePath = "page"
pluralizeListTitles = true

[params]
  Subtitle = "photography, coffee, technology and more"
  GithubID = "Bunker"
  TwitterID = "Bunker"
  AnalyticsID = "UA-2550570-4"
  Summary = false
  Content = true

[[menu.main]]
    name = "Home"
    pre = ""
    weight = -110
    identifier = "Home"
    url = "/"